# video device, on linux might be /dev/video<N>
video: 0

# name: str (optional)
#   a name to identify the device
# name: My Cute Camera

# capture_mode: str (optional), default='auto', in ['auto', 'any', 'dshow']
#   if auto, will try to use the best configuration mode
# capture_mode: 'auto'

# resolution: str (optional)
#   requested resolution in the format "<width>x<height>" in pixels
# resolution: 640x480

# resolutions: list of str, (optional)
#   available resolutions for this camera
# resolutions:
#  - 640x480
#  - 1280x720

# crop: str (optional)
#   requested crop in the format "<x_from>,<x_to>;<x_from>,<x_to>" in pixels
# resolution: 640x480

# threaded: bool (optional) default=True,
#   if True the captures are made in a separate thread preventing GUI from blocking
# threaded: False

# compression: str (optional), default=None, in [
#    'XVID', # "XviD MPEG-4",
#    'MJPG', "Motion JPEG",
#    'H264': "H.264 / AVC",
#    'DIVX': "DivX MPEG-4",
#    'MP4V': "MPEG-4 Video",
#    'I420': "Uncompressed YUV format"
# ]
# compression: 'MJPG'
