# video device, on linux might be /dev/video<N>
video: 0

# name: str (optional)
#   a name to identify the device
# name: My Cute Camera

# capture_mode: str (optional), default='auto', in ['auto', 'any', 'dshow']
#   if auto, will try to use the best configuration mode
# capture_mode: 'auto'

# resolution: str (optional)
#   requested resolution in the format "<width>x<height>" in pixels
# resolution: 640x480

# resolutions: list of str, (optional)
#   available resolutions for this camera
# resolutions:
#  - 640x480
#  - 1280x720

# threaded: bool (optional) default=True,
#   if True the captures are made in a separate thread preventing GUI from blocking
# threaded: False

# camera_type: str (optional), default='mono', in ['mono', 'stereo']
#   if 'stereo' requested resolution width is twice the specified.
# camera_type: 'mono'
